### ISSUE TITLE
今天微博改版，脚本失效

### ISSUE THREAD

**Issue by tulip33** [neverweep/Weibo-Larger-Pics#1]
今天微博改版，图片变大不少，你的脚本完全失效，每天必用的脚本，保存原图非常方便，望跟进修复，谢谢！

**Comment by doio** [comment]
同求！！！！！！求适配最新微博！！！！

**Comment by neverweep** [comment]
已经可以显示了，不过没有仔细测试，大部分图应该都没事~

**Comment by tulip33** [comment]
1.2.5.1能显示了，感谢！

**Comment by tulip33** [comment]
另，greasyfork.org怎么不能留言了？一点留言就到首页，所以才找到这里反馈

**Comment by neverweep** [comment]
谁知道，我都好久没上过greasyfork了。。。
