### ISSUE TITLE
https下画廊模式加载http图片不成功

### ISSUE THREAD

**Issue by iyh** [neverweep/Weibo-Larger-Pics#3]
>Mixed Content: The page at 'https://weibo.com/*/*' was loaded over HTTPS, but requested an insecure image 'http://ww3.sinaimg.cn/large/*.jpg'. This request has been blocked; the content must be served over HTTPS.

画廊模式在https访问时 加载的仍是http的图片，会被chrome屏蔽加载 所以会一直提示“正在加载”

**Comment by neverweep** [comment]
下个版本会修复这个问题，感谢反馈
